# Generated by Django 3.0.5 on 2020-04-10 17:25

from django.db import migrations, models
import pmapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=pmapp.models.get_image_path),
        ),
    ]
