# Generated by Django 3.0.5 on 2020-04-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0002_auto_20200410_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
