# Generated by Django 3.0.5 on 2020-04-14 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmapp', '0005_auto_20200414_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
